add custom params to deploy demo
Esri/solution.js pull request #697
Opened 2021-07-30 21:12 UTC by jmhauck

Allows us to pass custom params like wkid or the upcoming feature service id.

2021-07-30 22:46 UTC, MikeTschudi requested changes
The Custom Params box seems as if it should be optional if one doesn't have custom parameters, but this doesn't work: "{}" has to be supplied as a minimum. Is this a requirement? Can we change the web page to something like
```js
const customParams = document.getElementById("customParams").value || "{}";
```
so that the custom parameters have a default value?

2021-07-30 22:46 UTC, MikeTschudi commented on demos/src/deploy-solution-main.ts
> +      params: JSON.parse(customParams)
If a solution template is supplied and the Custom Params input box is left alone, "Deploying..." appears on the screen, the app hangs, and the debugger shows "Uncaught SyntaxError: Unexpected end of JSON input".

2021-07-30 22:46 UTC, MikeTschudi commented on demos/src/deploy-solution-main.ts
> +      params: JSON.parse(customParams)
If a folder of solution templates is supplied and the Custom Params input box is left alone, "Deploying..." appears on the screen and then is replaced by "{}".

2021-08-02 20:30 UTC, jmhauck commented
Thanks @MikeTschudi

2021-08-02 20:40 UTC, MikeTschudi approved these changes

2021-08-02 21:16 UTC, merged